version: "3.9"

services:
    db:
        image: postgres:15-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    app:
        build: .
        env_file:
            - .env
        volumes:
            - .:/var/www/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        stdin_open: true
        tty: true

volumes:
    postgres_data:
