version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    stdin_open: true
    tty: true
    networks:
      - backend-net

  database:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=password
    networks:
      - backend-net

  cache:
    image: redis:7.0-alpine
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui

networks:
  backend-net:
    driver: bridge

volumes:
  postgres_data:
